[project]
name = "never-back-down"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.129.1",
    "openai>=2.21.0",
    "pydantic>=2.12.5",
    "uvicorn>=0.41.0",
]
